### ISSUE TITLE
[DÚVIDA] - Contribuição

### ISSUE THREAD

**Issue by luan0ap** [diogomoretti/eleicoes2018#2]
Olá, gostaria de saber se o projeto está aberto a contribuições? Se sim, como foi feito o bundle dele? No `package.json` não apresenta um ambiente de desenvolvimento.

**Comment by diogomoretti** [comment]
Sim, o projeto está aberto sim. Dá um fetch que foi atualizado algumas dependências... ou se preferir, pode forkar novamente =]
