### ISSUE TITLE
Add a more descriptive "README"

### ISSUE THREAD

**Issue by Pedro-Mendes** [diogomoretti/eleicoes2018#8]
Oi Diogo, tudo bem?

Cara achei muito legal esse repo aqui, será que é possível colocar um README mais explicativo?
Acho que até ajudaria a atingir mais pessoas.

Thanks!

**Comment by diogomoretti** [comment]
Vou colocar sim, principalmente "como rodar"... se quiser, sinta-se a vontade para abrir um PR ❤️
